# Generated by Django 4.1.3 on 2022-12-18 09:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycolor',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='color', unique=True),
        ),
        migrations.AlterField(
            model_name='categorygender',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='gender', unique=True),
        ),
        migrations.AlterField(
            model_name='categorysize',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='size', unique=True),
        ),
    ]
